name: 'Setup tarantool'
description: 'Setup tarantool environment and add it to the PATH'
inputs:
  tarantool-version:
    description: 'Tarantool version'
    default: '2.5'
  cache-key:
    description: >
      Custom key used for caching apt packages.
      Default is "tarantool-<VERSION>-<RUNNER.OS>"
    required: false
runs:
  using: 'node12'
  main: dist/main/index.js
