name: 'Setup tarantool'
description: 'Setup tarantool environment with caching'
branding:
  icon: 'code'
  color: 'red'
inputs:
  tarantool-version:
    description: Tarantool version
  cache-key:
    description: Custom key used for APT packages caching
    required: false
runs:
  using: 'node12'
  main: dist/main/index.js
