name: Build and Test

on:
  push:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          tarantool-version: '2.6'
