name: Build and Test

on:
  push:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest]
        tarantool: ['1.10', '2.4', '2.5', '2.6']
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup from scratch
        uses: ./
        with:
          tarantool-version: ${{ matrix.tarantool }}
          cache-key: tarantool-${{ matrix.tarantool }}-${{ runner.os }}-${{ github.run_id }}

      - name: Uninstall tarantool
        run: sudo apt remove tarantool tarantool-dev tarantool-common

      - name: Setup from cache
        uses: ./
        with:
          tarantool-version: ${{ matrix.tarantool }}
          cache-key: tarantool-${{ matrix.tarantool }}-${{ runner.os }}-${{ github.run_id }}

      - run: tarantool --version
      - name: Check version
        run: |
          T=$(tarantool -e 'print(_TARANTOOL:match("%d+%.%d+")); os.exit()')
          if [ "$T" != "${{ matrix.tarantool }}" ]; then
            echo "Tarantool version is $T, expected ${{ matrix.tarantool }}"
            exit 1
          fi
