name: Build and Test

on:
  push:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-20.04]
        tarantool: ['1.10', '2.4', '2.5', '2.6', '2.7']
        include:
        - {runs-on: ubuntu-18.04, tarantool: '1.10'}
        - {runs-on: ubuntu-16.04, tarantool: '1.10'}
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup from scratch
        uses: ./
        with:
          tarantool-version: ${{ matrix.tarantool }}
          cache-key: tarantool-${{ matrix.tarantool }}-${{ matrix.runs-on }}-${{ github.run_id }}

      - name: Uninstall tarantool
        run: sudo apt-get -y remove tarantool tarantool-dev tarantool-common

      - name: Setup from cache
        uses: ./
        with:
          tarantool-version: ${{ matrix.tarantool }}
          cache-key: tarantool-${{ matrix.tarantool }}-${{ matrix.runs-on }}-${{ github.run_id }}

      - name: Check version
        run: |
          T=$(tarantool -e 'print(_TARANTOOL:match("%d+%.%d+")); os.exit()')
          if [ "$T" != "${{ matrix.tarantool }}" ]; then
            echo "Tarantool version is $T, expected ${{ matrix.tarantool }}"
            exit 1
          else
            echo "Tarantool version is $T, as expected"
          fi

  test-concurrency:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-20.04, ubuntu-20.04, ubuntu-20.04]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Tarantool
        uses: ./
        with:
          tarantool-version: '1.10'
          cache-key: test-concurrency-${{ github.run_id }}
